# Generated by Django 5.1.11 on 2025-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('cuit', models.CharField(db_column='Cuit', max_length=45)),
                ('producto', models.CharField(blank=True, db_column='Producto', max_length=45, null=True)),
                ('cantidad', models.CharField(blank=True, db_column='Cantidad', max_length=7, null=True)),
            ],
            options={
                'db_table': 'cambios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(db_column='cuit', max_length=13, unique=True)),
                ('razons', models.CharField(db_column='RazonS', max_length=60)),
                ('direccion', models.CharField(db_column='Direccion', max_length=45)),
                ('provincia', models.CharField(db_column='Provincia', max_length=45)),
                ('alias', models.CharField(blank=True, db_column='Alias', max_length=45, null=True)),
                ('lista', models.CharField(db_column='Lista', max_length=45)),
                ('descuento', models.CharField(db_column='Descuento', max_length=45)),
                ('recargo', models.CharField(db_column='Recargo', max_length=45)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=3, null=True)),
            ],
            options={
                'db_table': 'comprobantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentastc',
            fields=[
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cuentastc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('idgrupo', models.IntegerField(db_column='IdGrupo', primary_key=True, serialize=False)),
                ('nombregrupo', models.CharField(blank=True, db_column='NombreGrupo', max_length=50, null=True)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'listas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=70, null=True)),
                ('precio', models.CharField(blank=True, db_column='Precio', max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('iva', models.CharField(db_column='Iva', max_length=45)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespIva',
            fields=[
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=2)),
            ],
            options={
                'db_table': 'resp_iva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(db_column='Producto', max_length=45)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=10)),
                ('precio_u', models.CharField(db_column='Precio_U', max_length=45)),
                ('cambio', models.CharField(db_column='Cambio', max_length=8)),
                ('total', models.CharField(db_column='Total', max_length=45)),
            ],
            options={
                'db_table': 'venta_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('comprobante', models.CharField(db_column='Comprobante', max_length=45)),
                ('n_fact', models.CharField(db_column='N_fact', max_length=13)),
                ('pan105', models.CharField(blank=True, db_column='Pan105', max_length=45, null=True)),
                ('pan21', models.CharField(blank=True, db_column='Pan21', max_length=45, null=True)),
                ('exento', models.CharField(blank=True, db_column='Exento', max_length=45, null=True)),
                ('iva105', models.CharField(blank=True, db_column='Iva105', max_length=45, null=True)),
                ('iva21', models.CharField(blank=True, db_column='Iva21', max_length=45, null=True)),
                ('otros', models.CharField(blank=True, db_column='Otros', max_length=45, null=True)),
                ('total', models.CharField(blank=True, db_column='Total', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('nombre', models.CharField(db_column='Nombre', max_length=45, primary_key=True, serialize=False)),
                ('dgr', models.CharField(db_column='Dgr', max_length=5)),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
    ]
